version: "3"

services:
  typesense:
    container_name: typesense
    image: typesense/typesense:0.23.1
    ports:
      - 8108:8108
    environment:
      - TYPESENSE_DATA_DIR=/data
      - TYPESENSE_API_KEY=Mx3ofRw7LrB9yE1RpEi2P3Kwv7ktzqDA
    volumes:
      - typesense-data:/data

volumes:
  typesense-data:
    driver: local