version: "3"

services:
  typesense:
    container_name: typesense
    image: typesense/typesense:0.23.1
    ports:
      - 8108:8108
    environment:
      - TYPESENSE_DATA_DIR=/data
      - TYPESENSE_API_KEY=xyz # default admin key
    volumes:
      - type: volume
        source: typesense-data
        target: /data

volumes:
  typesense-data:
    driver: local